### ISSUE TITLE
Proper Deterministic Randomness for Shamir & sskr

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/bc-seedtool-cli#32]
A challenge for bc-shamir is that it also needs randomness separately from seed randomness, so that when testing  on different implementaions, when using deterministic flag, the exact same values should be output for all the shares, even though with real shamir randomness all the variants will restore back to the correct seed

So we need a way to expand the randomness in a deterministic way for testing multiple implementations of sskr against each other.

**Comment by wolfmcnally** [comment]
This is already in bc-shamir. bc-sskr uses the same API to take a function that generates random numbers, and passes it on to bc-shamir.
