### ISSUE TITLE
Add Dockerfile to make the build process more easy, secure, and hermetic

### ISSUE THREAD

**Issue by secinthenet** [BlockchainCommons/bc-seedtool-cli#44]
This issue is relevant to all BlockchainCommons tools.
The current build process requires installing llvm 10 (and possibly other dependencies in the future), which requires build privileges and is not always desirable. In addition, building is not hermetic, it can be affected be anything already installed on the build machine.
A better approach, both in terms of build reproduciblity and user friendliness, is providing a Dockerfile and/or using a build system such as Bazel.

**Comment by secinthenet** [comment]
I sent a PR that adds a Dockerfile. If it's merged, this issue can be closed, but I'll open another issue to make the build reproducible (Docker doesn't guarantee that).

**Comment by wolfmcnally** [comment]
> I sent a PR that adds a Dockerfile. If it's merged, this issue can be closed, but I'll open another issue to make the build reproducible (Docker doesn't guarantee that).

The only problem with your PR was that it wasn't GPG signed. See comments there.
