### ISSUE TITLE
What about encoding a shard as bech32?

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/bc-seedtool-cli#8]
After seeing the sample output of:

```
seedtool --out bech32
```

I'm not sure `-out bech32` is always correct. Can you output a Shamir shard as bech32? You should also be able to do that. Which leads to the problem of how seedtool knows that a seed put into bech32 gets the prefix seed, but a Shamir shard -out bech32 gets another prefix, like skr0 (secret key recovery 0 as we know there is VSS on the way). That is why I've been puzzling no prefixes and version numbers.

Ideas on how we can also output a shard as bech32 and not mnemonics?

-- Christopher Allen

**Comment by wolfmcnally** [comment]
Bech32 was replaced with BC32, which was replaced with Bytewords.
